### ISSUE TITLE
What problem does this solve? Do I need drivers in the kexts folder?

### ISSUE THREAD

**Issue by SXQBW** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#4]
https://github.com/bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh/blob/aafa4da1c3a35ddbc3d6fa591ad57383cf478eff/EFI/OC/config.plist#L254

**Comment by bestplay9384** [comment]
Hey,

There was some MacOS Version that broke AMD GPUs to work in hackintosh. What community did then was to add some flags that made Your custom GPU (GPU that Apple do not use in their builds, but their drivers should cover it) being detected as some apple-provided AMD GPU. 

In my case it was to change AMD Radeon RX 5700 XT to AMD Radeom W5700X so the driver worked fine on it. 
I managed to left this flags even after they fixed it all - because during my research it turned out that Geekbench gives me better results in testing when this info is in OC config.

I do not understand the second question. Kexts are in OC/Kexts directory, while drivers are in OC/Drivers.
Minimal configuration should contain these: [Refers to Dortania official OpenCore Docs](https://dortania.github.io/OpenCore-Post-Install/universal/update.html#_3-replace-the-opencore-files-with-the-ones-you-just-downloaded). But in my case i have some other drivers to fully cover my hardware & enable some debugging abilities when i need it.

**Comment by SXQBW** [comment]
thanks
