### ISSUE TITLE
I can't find any information about "-ctssmt", may I ask what problem it mainly solves?

### ISSUE THREAD

**Issue by SXQBW** [bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh#5]
https://github.com/bestplay9384/EFI-GIGABYTE-Z690-Gaming-X-DDR4-12700K-RX5700XT-Hackintosh/blob/aafa4da1c3a35ddbc3d6fa591ad57383cf478eff/EFI/OC/config.plist#L919

**Comment by bestplay9384** [comment]
Oh You're right! :) 

It is a flag that enabled CpuTopologySync.kext in some initial versions of my EFI. As far as i remember it was some version compiled specially for Z690 series. Why it is not a part of EFI now? Because its abilites were integrated into OpenCore itself since some version (don't really remember which one). Flag can be surely removed :)
